### ISSUE TITLE
[suggestion] About publishing extension.

### ISSUE THREAD

**Issue by ilovefreesw** [hallzy/youtube-playlist-search#3]
I read you don't want to publish to Chrome web store because they charge 5 dollars registration fees. But what about Microsft Edge and Firefox? They are free. Can publish it there? Right ?

Thanks

**Comment by hallzy** [comment]
Before I go further, I don't have a single windows computer in my house and I moved to linux back in the Vista days. So I have never used Edge. I also don't use Firefox... so my knowledge of the 2 may not all be there.

I also don't have, and never have had a Mac, so I've also never used Safari (You didn't ask about safari, but while I am here I thought I'd mention it)

## Firefox

The extension system for Firefox is different enough to chrome that my extension would not work on Firefox as is.

Specifically, the declarativeContent API, and the identity.getAuthToken api.

I am by no means an expert on extension development (this is the first and only extension I have ever made), but from a quick google search it doesn't even look like you can get auth tokens for things like the youtube api in firefox

if I can't get auth tokens for the youtube api, then there is nothing I can do about Firefox.

I also don't use firefox as mentioned earlier, so naturally it would be less tested, since I wouldn't be using it everyday in firefox

## Edge

In theory, edge should be easy since it is a fork of the chromium project. I haven't seen any mention of a registration fee either.

However, Edge would get absolutely 0 testing from me because I do not have access to the browser. So any bugs found by others that exist just in edge will be effectively impossible for me to fix alone.

I wouldn't even know if it even worked at all right after submission.

## Safari

You didn't ask but thought I would mention it anyways. I know far less about safari than even Edge (which is saying a lot).

I have absolutely no idea how compatible safari is with chrome extensions (my guess would be, not at all), and same issue as with edge. It would see absolutely 0 testing from me, and any bugs that came up specific to safari would be very hard for me to fix.

**Comment by Suleman-Elahi** [comment]
Can publish to Edge Addons now. It's free and not as strict as Chrome developer dashboard. Also, can submit it to Opera Store.
